/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateOrder_GUI.java
 *
 * Created on Jul 7, 2011, 4:26:33 PM
 */
package jaydee.com.gui;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jaydee.engine.AddNewStock;
import jaydee.engine.Supplier;
import jaydee.engine.SupplierDrug;
import jaydee.engine.User;
import reusable.DBFunctions;

/**
 *
 * @author Wachanga
 */
public class Order_GUI extends javax.swing.JInternalFrame {

    /** Creates new form CreateOrder_GUI */
    Vector<Supplier> supplierlist;
    Vector<SupplierDrug> druglist_Supplier;
 
    ArrayList<AddNewStock> to_insert;
    
    int index_suppliers;
    int index_drugs;
    
    int index_batch_list = 0;
    DBFunctions db;
    
    User user;
    
    boolean end_of_init = false;
    public Order_GUI(User user) {
        this.user = user;
        db = new DBFunctions();
        initComponents();
        initAddNewStockForm();
    }
    
    
     public final void initAddNewStockForm(){ 
        jListBatchList.removeAll();
        String [] empty = new String[2];
        jListBatchList.setListData(empty);
        initSuppliersANDDrugs();
        txtBatchNumber_Stock.setText(loadBatchNumber()+"");
        to_insert = new ArrayList<AddNewStock>();
    }    
    public void initSuppliersANDDrugs(){
        index_suppliers = 0;
        index_drugs = 0;
        supplierlist = new Vector<Supplier>();
        //Remove all items
        jcbox_Suppliers.removeAllItems();
        //Init the suppliers
        boolean found = false;
        String query = "SELECT sid FROM supplier ORDER BY name;";
        try {
            ResultSet rs = db.con.createStatement().executeQuery(query);
            supplierlist.removeAllElements();
            while (rs.next()) {
                supplierlist.add(new Supplier(rs.getInt("sid")));
                found = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventory_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (found) {
        for (int i = 0; i < supplierlist.size(); i++) {
            jcbox_Suppliers.addItem(supplierlist.get(i).name);
        }
        jcbox_Suppliers.setSelectedIndex(index_suppliers);
        } else {
            System.err.println("The database has no suppliers");
        }        
       initSupplierDrug(supplierlist.get(jcbox_Suppliers.getSelectedIndex()).sid);         
    }
    public void initSupplierDrug(int sup){
        jcbox_Drugs.removeAllItems();
        druglist_Supplier = new Vector<SupplierDrug>();
        //Now to init the drugs
        boolean found = false;
        String query = "SELECT s.sid,s.did,s.cost,s.ssid FROM supplier_stock s,drugs d WHERE sid=" + sup + " AND d.did=s.did ORDER BY d.name;";
        try {
            ResultSet rs = db.con.createStatement().executeQuery(query);
            druglist_Supplier.removeAllElements();
            while (rs.next()) {
                druglist_Supplier.add(new SupplierDrug(rs.getInt("sid"), rs.getInt("did"), rs.getDouble("cost")));
                found = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(DrugEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (found) {for (int i = 0; i < druglist_Supplier.size(); i++) {
            jcbox_Drugs.addItem(druglist_Supplier.get(i).drug.name);
        }
        jcbox_Drugs.setSelectedIndex(index_drugs);
        } else {
            System.err.println("The supplier has no drugs set in the database");
        }
    }    
    public final int loadBatchNumber(){
        int batch_number = -1;
        String query = "SELECT MAX(`batch_number`) FROM inventory;";
        try{
            ResultSet rs = db.stmt.executeQuery(query);
        while(rs.next()){
            batch_number = rs.getInt(1);
        }
        }catch (SQLException ex) {
            Logger.getLogger(Order_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return (batch_number+1);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jcbox_Drugs = new javax.swing.JComboBox();
        jcbox_Suppliers = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddToBatch = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBatchList = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtStockLeveAddNewStock = new javax.swing.JTextField();
        txtDrugNameAddNewStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierAddNewStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBatchNumber_Stock = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnSave_addnewstock = new javax.swing.JButton();
        btnCancel_addnewstock = new javax.swing.JButton();
        btnRemoveItem_addstock = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtQty_AddNewStock = new javax.swing.JTextField();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Order");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/jdp16.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Select the Supplier and drug"));

        jcbox_Drugs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbox_Suppliers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbox_Suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_SuppliersActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Supplier:");

        jLabel3.setText("Select Drug:");

        btnAddToBatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/Add16.png"))); // NOI18N
        btnAddToBatch.setText("Add");
        btnAddToBatch.setToolTipText("Add drug to batch");
        btnAddToBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBatchActionPerformed(evt);
            }
        });

        jLabel1.setText("Date:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbox_Suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcbox_Drugs, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddToBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(315, 315, 315))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddToBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbox_Suppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbox_Drugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jListBatchList.setBorder(javax.swing.BorderFactory.createTitledBorder("Batch List"));
        jListBatchList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListBatchList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListBatchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListBatchListValueChanged(evt);
            }
        });
        jListBatchList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jListBatchListFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jListBatchList);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Details"));

        jLabel5.setText("Supplier:");

        txtStockLeveAddNewStock.setEditable(false);
        txtStockLeveAddNewStock.setToolTipText("");

        txtDrugNameAddNewStock.setEditable(false);

        jLabel4.setText("Current Stock Level:");

        jLabel6.setText("Drug Name:");

        txtSupplierAddNewStock.setEditable(false);

        jLabel7.setText("Order Number:");

        txtBatchNumber_Stock.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(txtDrugNameAddNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBatchNumber_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSupplierAddNewStock)
                                .addComponent(txtStockLeveAddNewStock, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDrugNameAddNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtStockLeveAddNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSupplierAddNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBatchNumber_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnSave_addnewstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/Save24.png"))); // NOI18N
        btnSave_addnewstock.setText("Save");
        btnSave_addnewstock.setToolTipText("Save new batch to database");
        btnSave_addnewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_addnewstockActionPerformed(evt);
            }
        });

        btnCancel_addnewstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/cancel (2).png"))); // NOI18N
        btnCancel_addnewstock.setText("Cancel");
        btnCancel_addnewstock.setToolTipText("Resets the whole form");
        btnCancel_addnewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_addnewstockActionPerformed(evt);
            }
        });

        btnRemoveItem_addstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/Undo16.png"))); // NOI18N
        btnRemoveItem_addstock.setText("Remove Item");
        btnRemoveItem_addstock.setEnabled(false);
        btnRemoveItem_addstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItem_addstockActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Print Order Form");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave_addnewstock, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveItem_addstock, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(btnCancel_addnewstock))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel_addnewstock)
                    .addComponent(btnSave_addnewstock))
                .addGap(59, 59, 59)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveItem_addstock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Quantity:");

        txtQty_AddNewStock.setToolTipText("Enter the quantity");
        txtQty_AddNewStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQty_AddNewStockFocusLost(evt);
            }
        });
        txtQty_AddNewStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQty_AddNewStockKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(287, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(txtQty_AddNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(txtQty_AddNewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create Order", new javax.swing.ImageIcon(getClass().getResource("/com/res/cashbox (1).png")), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbox_SuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_SuppliersActionPerformed
        int index = jcbox_Suppliers.getSelectedIndex();
        if(end_of_init && index >= 0)
            initSupplierDrug(supplierlist.get(jcbox_Suppliers.getSelectedIndex()).sid);
}//GEN-LAST:event_jcbox_SuppliersActionPerformed

    private void btnAddToBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBatchActionPerformed
        int qty = 0;
        if(!txtQty_AddNewStock.getText().isEmpty()){
            try{
                qty = Integer.parseInt(txtQty_AddNewStock.getText());
                System.err.println("Information Label");
            }catch(NumberFormatException e){
                e.printStackTrace();
                System.err.println("Please enter a number for the quantity");
            }
        }
        //to_insert.add(new AddNewStock(druglist_Supplier.get(jcbox_Drugs.getSelectedIndex()).drug, Integer.parseInt(txtBatchNumber_Stock.getText()),jDateChooserCurDate.getCalendar(),jDateChooserExpiry.getCalendar(),qty, supplierlist.get(jcbox_Suppliers.getSelectedIndex())));
        jListBatchList.removeAll();
        Vector<String> stringDrug = new Vector<String>();
        for (int i = 0; i < to_insert.size(); i++) {
            stringDrug.add(to_insert.get(i).drug.name);
        }
        jListBatchList.setListData(stringDrug);
}//GEN-LAST:event_btnAddToBatchActionPerformed

    private void jListBatchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListBatchListValueChanged
        index_batch_list = jListBatchList.getSelectedIndex();
        if (index_batch_list > -1) {
            txtDrugNameAddNewStock.setText(to_insert.get(index_batch_list).drug.name);
            txtBatchNumber_Stock.setText(to_insert.get(index_batch_list).batch_number+"");
            int difference = to_insert.get(index_batch_list).d_const.difference();
            txtStockLeveAddNewStock.setText(difference+"");
            txtSupplierAddNewStock.setText(to_insert.get(index_batch_list).s.name);
            txtQty_AddNewStock.setText(to_insert.get(index_batch_list).qty+"");
        }
}//GEN-LAST:event_jListBatchListValueChanged

    private void jListBatchListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListBatchListFocusGained
        btnRemoveItem_addstock.setEnabled(true);
}//GEN-LAST:event_jListBatchListFocusGained

    private void btnSave_addnewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_addnewstockActionPerformed
        boolean success = false;
        for(int i = 0; i < to_insert.size(); i ++){
//            if(!insertIntoDB(i)){
//                success = false;
//                break;
//            }else{
//                success = true;
//            }
        }
        if(success){
            System.err.println("All new stock has been saved successfully.");
        }else{
            System.err.println("Some changes were lost and there was an error saving them to the database");
        }
}//GEN-LAST:event_btnSave_addnewstockActionPerformed

    private void btnCancel_addnewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_addnewstockActionPerformed
        URL url = Inventory_UI.class.getResource("/com/res/jdp24.png");
        Icon icon = new ImageIcon(Toolkit.getDefaultToolkit().createImage(url));
        if(JOptionPane.showConfirmDialog(this, "Are you sure you wish to reset the form\nYou will lose any unsaved data","Cancel All Changes", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,icon) == JOptionPane.YES_OPTION){
            initAddNewStockForm();
        }
}//GEN-LAST:event_btnCancel_addnewstockActionPerformed

    private void btnRemoveItem_addstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItem_addstockActionPerformed
        if(to_insert.size() > 0){
            to_insert.remove(jListBatchList.getSelectedIndex());
            jListBatchList.removeAll();
            jListBatchList.setListData(to_insert.toArray());
        }
        btnRemoveItem_addstock.setEnabled(false);
}//GEN-LAST:event_btnRemoveItem_addstockActionPerformed

    private void txtQty_AddNewStockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQty_AddNewStockFocusLost
        int qty = 0;
        if(!txtQty_AddNewStock.getText().isEmpty()){
            try{
                qty = Integer.parseInt(txtQty_AddNewStock.getText());
                System.err.println("Information Label");
            }catch(NumberFormatException e){
               System.err.println("Please enter a number for the quantity");
            }
        }to_insert.get(jListBatchList.getSelectedIndex()).qty = qty;
}//GEN-LAST:event_txtQty_AddNewStockFocusLost

    private void txtQty_AddNewStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQty_AddNewStockKeyPressed
        int index = jcbox_Suppliers.getSelectedIndex();
        int qty = 0;
        if(!txtQty_AddNewStock.getText().isEmpty()){
            try{
                qty = Integer.parseInt(txtQty_AddNewStock.getText());
                System.err.println("Information Label");
            }catch(NumberFormatException e){
                System.err.println("Please enter a number for the quantity");
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && index > -1 && qty > 0){
            to_insert.get(jListBatchList.getSelectedIndex()).qty = qty;
        }
}//GEN-LAST:event_txtQty_AddNewStockKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBatch;
    private javax.swing.JButton btnCancel_addnewstock;
    private javax.swing.JButton btnRemoveItem_addstock;
    private javax.swing.JButton btnSave_addnewstock;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jListBatchList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jcbox_Drugs;
    private javax.swing.JComboBox jcbox_Suppliers;
    private javax.swing.JTextField txtBatchNumber_Stock;
    private javax.swing.JTextField txtDrugNameAddNewStock;
    private javax.swing.JTextField txtQty_AddNewStock;
    private javax.swing.JTextField txtStockLeveAddNewStock;
    private javax.swing.JTextField txtSupplierAddNewStock;
    // End of variables declaration//GEN-END:variables
}
