/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnterPOSDetails.java
 *
 * Created on Jul 23, 2011, 4:38:47 AM
 */
package jaydee.com.a_ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import jaydee.engine.Constants;
import jaydee.engine.Engine_POS;

/**
 *
 * @author Wachanga
 */
public class EnterPOSDetails extends javax.swing.JFrame {

    /** Creates new form EnterPOSDetails */
    //FindItem_POS find;
    Engine_POS eng;
    jaydee.com.a_ui.POS pos;
    boolean end_of_init;
    int val = -1;//For editing the values only
    public EnterPOSDetails(jaydee.com.a_ui.POS pos) {
        end_of_init = false;
        this.pos = pos;
        this.eng = pos.pos_eng;
        initComponents();
        setTheBounds(getWidth(), getHeight());   
        setAlwaysOnTop(true);
        end_of_init = true;
    }
    
    int r = -1;
    int c = -1;
    
    public EnterPOSDetails(jaydee.com.a_ui.POS pos, int val, int r, int c) {
        this.r = r;
        this.c = c;
        end_of_init = false;
        this.pos = pos;
        this.val = val;
        this.eng = pos.pos.get(val);
        initComponents();
        setTheBounds(getWidth(), getHeight());   
        setAlwaysOnTop(true);
        end_of_init = true;
    }
    
     public final void setTheBounds(int a, int b) {
        int width = a;
        int height = b;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - width) / 2;
        int y = (screen.height - height) / 2;
        setBounds(x, y, width, height);
        URL url = EnterPOSDetails.class.getResource("/com/res/jdp24.png");
        setIconImage(Toolkit.getDefaultToolkit().createImage(url));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jCheckBoxDiscount = new javax.swing.JCheckBox();
        jCheckBoxTax = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtSelectedItem = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_info = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POS Values");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Quantity:");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        jLabel4.setText("Price:");

        txtPrice.setEditable(false);

        jCheckBoxDiscount.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxDiscount.setText("Discount");

        jCheckBoxTax.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTax.setText("Tax");

        jLabel2.setText("Item Name:");

        txtSelectedItem.setEditable(false);

        btnAddItem.setText("Save");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Select the Item");

        lbl_info.setText("Information Label");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxTax)
                                    .addComponent(jCheckBoxDiscount)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtSelectedItem))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_info, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxDiscount)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxTax)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lbl_info))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        process();
        dispose();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       eng = null;
       dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        process();
    }//GEN-LAST:event_txtQuantityActionPerformed

    
    public void process(){
        if(end_of_init){
            String qty_S = txtQuantity.getText();
//        if(eng.drug != null){
//            System.out.println("Item:"+ eng.drug.name+"  "+qty_S);
//        }
        if(val < 0 ){
            setDiscountTax();
            try{
                int qty = Integer.parseInt(qty_S);
                eng.qty = qty;
                pos.addItem(eng);
                pos.pos.add(eng);
                System.out.println("Added new to POS "+eng.drug.name);
                dispose();
            }catch(NumberFormatException e){
                lbl_info.setText("Please enter a correct number");
            }
        }
        else{
            try{
                int temp = pos.pos.get(val).qty;
                int qty = Integer.parseInt(qty_S);
                eng.qty = qty;
                pos.pos.get(val).qty = qty;
                double price = pos.pos.get(val).drug.price;
                pos.editItem(qty, r, c);
                System.out.println("the old and new qty are: "+temp+ "   "+qty);
                pos.computeSum((temp - qty) * price);
                dispose();
            }catch(NumberFormatException e){
                lbl_info.setText("Please enter a correct number");
            }
        }
        }
    }
    
    
    public void setDiscountTax(){
        Constants con = new Constants();
        if(jCheckBoxDiscount.isSelected()){
            eng.discount = con.DISCOUNT;
        }
        if(jCheckBoxTax.isSelected()){
            eng.tax = con.VALUE_ADDED_TAX;
        }
        eng.computeSum();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new EnterPOSDetails(new Engine_POS(null, WIDTH, WIDTH)).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancel;
    public javax.swing.JCheckBox jCheckBoxDiscount;
    public javax.swing.JCheckBox jCheckBoxTax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_info;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtQuantity;
    public javax.swing.JTextField txtSelectedItem;
    // End of variables declaration//GEN-END:variables
}
