/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FindItem_POS.java
 *
 * Created on Jul 21, 2011, 3:06:20 PM
 */
package jaydee.com.a_ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import jaydee.engine.Drug;
import jaydee.engine.Engine_POS;
import reusable.DBFunctions;

/**
 *
 * @author Wachanga
 */
public class FindItem_POS extends javax.swing.JFrame {

    /** Creates new form FindItem_POS */
    DBFunctions db;
    String query_name;
    Vector<Engine_POS> listData;
    Engine_POS eng;
    boolean end_of_init;
//    public FindItem_POS(Engine_POS eng) {
//        end_of_init = false;
//        this.eng = eng;
//        db = new DBFunctions();
//        initComponents();
//        query_name = "%";
//        txtName.setText(query_name);
//        setTheBounds(getWidth(), getHeight());   
//        setAlwaysOnTop(true);
//        end_of_init = true;
//    }
    
    jaydee.com.a_ui.POS pos;
    public FindItem_POS(jaydee.com.a_ui.POS pos) {
        end_of_init = false;
        this.pos = pos;
        this.eng = pos.pos_eng;
        db = new DBFunctions();
        initComponents();
        query_name = pos.txtItemAdd.getText();
        txtName.setText(query_name);
        System.out.println("The pos engine = "+query_name);
        setTheBounds(getWidth(), getHeight());   
        setAlwaysOnTop(true);
        if(!txtName.getText().isEmpty()){
                query_name = txtName.getText();
            }else{
                query_name = "%";
            }
            selectItemsFromDB();
        end_of_init = true;        
    }
     public final boolean selectItemsFromDB(){
         end_of_init = false;
        boolean found =false;
        if(txtName.getText().isEmpty()){
            txtName.setText("%");
        }
        query_name = txtName.getText();
        String query = "SELECT DISTINCT * FROM drugs WHERE name LIKE '%"+query_name+"%' OR  code LIKE '%"+query_name+"%';";
        //Remove all items on jlist
        
        listData = new Vector<Engine_POS>();
        Vector<String> list_names = new Vector<String>();
        ResultSet rs;
        try {
            rs = db.stmt.executeQuery(query);
       
        while(rs.next()){
            Engine_POS p = new Engine_POS(new Drug(rs.getInt("did")), 0);
            listData.add(p);
            list_names.add(p.drug.name+" ::: "+p.drug.code);                    
        }
         } catch (SQLException ex) {
            Logger.getLogger(FindItem_POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jlistItems.setListData(list_names);
        jlistItems.setSelectedIndex(0);
        end_of_init = false;
        return found;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSearchName = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistItems = new javax.swing.JList();
        btnSelect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find Item : POS - JayDee Pharmaceuticals");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Item Name or Code:");

        txtName.setText("Item");
        txtName.setToolTipText("Enter the item name or code");
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        btnSearchName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/search (1).png"))); // NOI18N
        btnSearchName.setText("Search");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        jlistItems.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlistItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlistItems);

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/Save16.png"))); // NOI18N
        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/cancel (1).png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchName)
                    .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchName))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSelect)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancel)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER){
           performSearch();
        }
}//GEN-LAST:event_txtNameKeyPressed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        performSearch();
}//GEN-LAST:event_btnSearchNameActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        int index = jlistItems.getSelectedIndex();
        System.out.println("The index is "+index);
        if(index > -1){  
         System.out.println("The index is "+index);   
            eng = listData.get(index);
            this.setVisible(false);
            pos.pos_eng = eng;
            pos.txtSelectedItem.setText(eng.drug.name);
            EnterPOSDetails enter = new EnterPOSDetails(pos);
            enter.txtPrice.setText(eng.drug.price+"");
            enter.txtQuantity.setText("");
            enter.txtSelectedItem.setText(eng.drug.name);
            enter.setVisible(true);
            dispose();            
        }  
}//GEN-LAST:event_btnSelectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        eng = null;
        dispose();
}//GEN-LAST:event_btnCancelActionPerformed
    public void performSearch(){
        if(!txtName.getText().isEmpty()){
            query_name = txtName.getText();
        }else{
            query_name = "%";
        }
        selectItemsFromDB();
    }
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new FindItem_POS(new Engine_POS(null, WIDTH, WIDTH)).setVisible(true);
//            }
//        });
//    }
    
    
    
    
    public final void setTheBounds(int a, int b) {
        int width = a;
        int height = b;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - width) / 2;
        int y = (screen.height - height) / 2;
        setBounds(x, y, width, height);
        URL url = FindItem_POS.class.getResource("/com/res/jdp24.png");
        setIconImage(Toolkit.getDefaultToolkit().createImage(url));
    }
    
//    public FindItem_POS(String search_query, Engine_POS eng) {
//        end_of_init = false;
//        this.eng = eng;
//        db = new DBFunctions();
//        initComponents();
//        query_name = search_query;
//        txtName.setText(query_name);
//        end_of_init = true;
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlistItems;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
