/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * POS.java
 *
 * Created on Jul 21, 2011, 1:48:25 PM
 */
package jaydee.com.a_ui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import jaydee.com.gui.ProcessPayment;
import jaydee.engine.Drug;
import jaydee.engine.Engine_POS;
import jaydee.engine.User;
import reusable.DBFunctions;

/**
 *
 * @author Wachanga
 */
public class POS extends javax.swing.JInternalFrame {

    /** Creates new form POS */
    DBFunctions db;
    Vector<Drug> druglist;
    Vector<String> stringDrug;
    int index = 0;
    TableModel model;
    TableColumnModel tcmodel;
    DefaultTableModel tblmodel;
    public Engine_POS pos_eng;
    public ArrayList<Engine_POS> pos;
    FindItem_POS find;
    boolean end_of_init;
    public User user;
    
    public double sum = 0.0;
    
    public POS(User user) { 
        this.user = user;
        end_of_init = false;
        pos = new ArrayList<Engine_POS>();
        db = new DBFunctions();
        initComponents();
        initDrugsList();
        initTableModel();
        initActionKeys();
        end_of_init = true;
    }
    
    public final void initDrugsList(){
        druglist = new Vector<Drug>();
        boolean found = false;
            String query = "SELECT did FROM drugs;";
        try {
            ResultSet rs = db.stmt.executeQuery(query);            
            while(rs.next()){
                druglist.add(new Drug(rs.getInt("did")));
                found = true;
            }            
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        stringDrug = new Vector<String>();
        for(int i = 0; i < druglist.size(); i++){
            stringDrug.add(druglist.get(i).name);
        }
        if(found){
            //IMplement the if found clause***************
        }else{
            JOptionPane.showMessageDialog(this, "Please enter drugs into the database");
        }
    }
    
    
    public final void initTableModel() {
        this.model = tblStudents.getModel();
        this.tcmodel = tblStudents.getColumnModel();
        TableColumn col = tcmodel.getColumn(0);
        col.setPreferredWidth(15);
        tblmodel = (DefaultTableModel) tblStudents.getModel();
        tblStudents.setModel(tblmodel);
    }
    
    
    public final void initActionKeys(){
        this.addKeyListener(new KeyAdapter() {
            @Override
        public void keyPressed(java.awt.event.KeyEvent evt) {
            if(evt.getKeyCode() == KeyEvent.VK_F2){                
                payCash();
        }
            if(evt.getKeyCode() == KeyEvent.VK_F6){ 
                 findItem();
        }
            if(evt.getKeyCode() == KeyEvent.VK_F5){                
                initDrugsList();
        }
            if(evt.getKeyCode() == KeyEvent.VK_F7){                
               removeItem();
        }
            if(evt.getKeyCode() == KeyEvent.VK_F12){                
                clearFields();
        }
            
            
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPayCash2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtItemAdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSelectedItem = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnEnterPOSDetails = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPayCash1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnFindItem = new javax.swing.JButton();
        btnRefreshLists = new javax.swing.JButton();
        btnRemoveItem1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnClear1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Point Of Sale");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/jdp16.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Process Payment"));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.00");
        lblTotal.setToolTipText("Grand Total");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Total: ");

        btnPayCash2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/checkout.png"))); // NOI18N
        btnPayCash2.setText("Process Payment (F2)");
        btnPayCash2.setToolTipText("Pay using Cash");
        btnPayCash2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayCash2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPayCash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayCash2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPayCash2)
                        .addGap(88, 88, 88))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTotal)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnPayCash2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Item"));

        jLabel7.setText("Item Code:");

        txtItemAdd.setToolTipText("Enter item code ");
        txtItemAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemAddKeyPressed(evt);
            }
        });

        jLabel2.setText("Selected Item:");

        txtSelectedItem.setEditable(false);

        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/shopping-bag.png"))); // NOI18N
        btnAddItem.setText("Add Item");
        btnAddItem.setToolTipText("Find or select an item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnEnterPOSDetails.setText("Enter Quantity (F3)");
        btnEnterPOSDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterPOSDetailsActionPerformed(evt);
            }
        });

        btnRemoveItem.setText("Remove (F7)");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSelectedItem, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnAddItem))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnEnterPOSDetails)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItem)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnterPOSDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnPayCash1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/checkout.png"))); // NOI18N
        btnPayCash1.setText("Pay - Cash (F2)");
        btnPayCash1.setToolTipText("Pay using Cash");
        btnPayCash1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayCash1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPayCash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayCash1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPayCash1);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator3);

        btnFindItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/shopping-bag.png"))); // NOI18N
        btnFindItem.setText("Find Item (F6)");
        btnFindItem.setToolTipText("Find or select an item");
        btnFindItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFindItem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFindItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindItemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFindItem);

        btnRefreshLists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/new.png"))); // NOI18N
        btnRefreshLists.setText("RefreshDrugs(F5)");
        btnRefreshLists.setToolTipText("Refresh Drugs List");
        btnRefreshLists.setFocusable(false);
        btnRefreshLists.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefreshLists.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefreshLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshListsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRefreshLists);

        btnRemoveItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/secure-payment.png"))); // NOI18N
        btnRemoveItem1.setText("Remove (F7)");
        btnRemoveItem1.setToolTipText("Remove an item");
        btnRemoveItem1.setFocusable(false);
        btnRemoveItem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveItem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemoveItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItem1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemoveItem1);
        jToolBar1.add(jSeparator2);

        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/empty-shopping-cart.png"))); // NOI18N
        btnClear1.setText("Clear (F12)");
        btnClear1.setToolTipText("Empty shopping cart");
        btnClear1.setFocusable(false);
        btnClear1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClear1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Item Name", "Item Code", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshListsActionPerformed
         initDrugsList();
}//GEN-LAST:event_btnRefreshListsActionPerformed

    private void btnFindItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindItemActionPerformed
         pos_eng = new Engine_POS(null, 0);
         find = new FindItem_POS(this);
         find.setVisible(true);
}//GEN-LAST:event_btnFindItemActionPerformed

    private void btnRemoveItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItem1ActionPerformed
        removeItem();
}//GEN-LAST:event_btnRemoveItem1ActionPerformed

    private void btnPayCash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayCash1ActionPerformed
       payCash();
    }//GEN-LAST:event_btnPayCash1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClear1ActionPerformed

    public void findItem(){
        pos_eng = new Engine_POS(null, 0);
                if(find == null){
                 find = new FindItem_POS(this);
                 find.setVisible(true);
                }
    }
    private void txtItemAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemAddKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           pos_eng = new Engine_POS(null, 0);
                if(find == null){
                 find = new FindItem_POS(this);
                 find.setVisible(true);
                }
        }
}//GEN-LAST:event_txtItemAddKeyPressed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        pos_eng = new Engine_POS(null, 0);
        if(find == null){
         find = new FindItem_POS(this);
         find.setVisible(true);
        }else{
            find.setVisible(true);
        }
}//GEN-LAST:event_btnAddItemActionPerformed

    private void btnPayCash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayCash2ActionPerformed
       payCash();
    }//GEN-LAST:event_btnPayCash2ActionPerformed

    private void btnEnterPOSDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterPOSDetailsActionPerformed
       int id = tblStudents.getSelectedRow();
       int r = id;
       int c = 3;
       index = tblmodel.getRowCount();
       if(id > -1 && index > -1){
           System.out.println("The row count "+index+"; the selected row: "+id +"; the arraysize: "+pos.size());
           EnterPOSDetails enter = new EnterPOSDetails(this, id, r, c);
            enter.txtPrice.setText(pos.get(id).drug.price+"");
            enter.txtQuantity.setText(pos.get(id).qty+"");
            enter.txtSelectedItem.setText(pos.get(id).drug.name);
            
            enter.setVisible(true);
       }
    }//GEN-LAST:event_btnEnterPOSDetailsActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        removeItem();
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    public void editItem(int qty, int r, int c){        
        tblmodel.setValueAt(qty, r, c);
    }
    
    public void addItem(Engine_POS eng){
        this.pos_eng = eng;
        index = tblmodel.getRowCount();
        if(end_of_init && pos_eng != null){
        if (tblmodel.getRowCount() <= 0) {
            index = 1;
        } else {
            index = tblmodel.getRowCount() + 1;
        }
        int c = 0; int k = 1;
                    for(int r = 0; r < tblmodel.getRowCount(); r++){
                        tblmodel.setValueAt(k, r, c);
                        k++;
                    }

        String[] data = {k + "", eng.drug.name, eng.drug.code, eng.qty +"", eng.drug.price+""};
               
        tblmodel.addRow(data);
        
        computeSum(eng.qty * eng.drug.price);
        
        }
    }
    
    public void payCash(){
        ProcessPayment pay = new ProcessPayment(this);
        pay.setVisible(true);
    }
    
    public void clearFields(){
        txtItemAdd.setText("");
        txtSelectedItem.setText("");
        for(int i = 0; i <= tblStudents.getRowCount(); i++){
            tblmodel.removeRow(i);
        }
            tblmodel.fireTableDataChanged();
            for(int i = 0; i < pos.size(); i++){
                pos.remove(i);
            }
            lblTotal.setText("");
            sum = 0.0;
    }
    
    public void removeItem(){
        if(tblmodel.getRowCount() > -1){            
            int row = tblStudents.getSelectedRow();
            double val = Double.parseDouble(tblmodel.getValueAt(row, 4).toString());
            int qty = Integer.parseInt(tblmodel.getValueAt(row, 3).toString());
            System.out.println("The val is "+val+" The qty is "+qty);
            computeSum(val * qty * -1);
            tblmodel.removeRow(row);
            tblmodel.fireTableDataChanged();
            pos.remove(row);
        }
    }
    public void computeSum(double val){  
        System.out.println("Compute sum() called\n");
         double total = sum;
         total += val;
        lblTotal.setText(total+"");
        sum = total;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnEnterPOSDetails;
    private javax.swing.JButton btnFindItem;
    private javax.swing.JButton btnPayCash1;
    private javax.swing.JButton btnPayCash2;
    private javax.swing.JButton btnRefreshLists;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnRemoveItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTotal;
    public javax.swing.JTable tblStudents;
    public javax.swing.JTextField txtItemAdd;
    public javax.swing.JTextField txtSelectedItem;
    // End of variables declaration//GEN-END:variables
}
