/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Jul 6, 2011, 3:08:17 PM
 */
package jaydee.com;

import com.users.Login;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import jaydee.About;
import jaydee.Help;
import jaydee.com.a_ui.DrugEditor;
import jaydee.com.a_ui.Drug_Supplier;
import jaydee.com.a_ui.Main_Admin;
import jaydee.com.a_ui.Supplier_GUI;
import jaydee.com.a_ui.Suppliers;
import jaydee.com.a_ui.Options;
import jaydee.com.a_ui.POS;
import jaydee.com.gui.Inventory_UI;
import jaydee.com.gui.Order_GUI;
import jaydee.engine.User;
import jaydee.engine.print.InventoryReport;
import jaydee.engine.print.PriceList;
import jaydee.engine.print.SalesReport;
import jaydee.engine.print.Supplier_Drug_List;
import reusable.DBFuncGUI;
import reusable.Info;

/**
 *
 * @author Wachanga
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    boolean end_of_init;
    User user;
    
    
    Suppliers suppliers;
    Supplier_GUI s_gui;
    DrugEditor d_editor;
    Drug_Supplier drug_supplier;
    Main_Admin main_admin;
    
    
    POS pos;
    Order_GUI order_gui;
    Inventory_UI inventory;
    
    public MainForm(User user) {
        this.user = user;
        end_of_init = false;
        
        initComponents();
        setTheBounds(getWidth(), getHeight());       
        
        if(user.usertype.equals("admin")){
            btnAdmin.setEnabled(true);
            jMenuItemAdmin.setEnabled(true);
        }
        
        txtUserWelcome.setText("Welcome, "+user.fullname);
        
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent ev){
                if(JOptionPane.showConfirmDialog(rootPane, "Are you sure you wish to exit? \nAny unsaved changes will be lost!","Exiting...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                     System.exit(0);
                }
            }
        });
        
        end_of_init = true;
    }

     public final void setTheBounds(int a, int b) {
        int width = a;
        int height = b;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - width) / 2;
        int y = (screen.height - height) / 2;
        setBounds(x, y, width, height);
        URL url = MainForm.class.getResource("/com/res/jdp24.png");
        setIconImage(Toolkit.getDefaultToolkit().createImage(url));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        txtUserWelcome = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSupplierDrugList = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnAdmin = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnPOS = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItemPOS = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLogout = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemViewSuppliers = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAddNewSuppliers = new javax.swing.JMenuItem();
        jMenuItemEditSuppliers = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAddSupplier = new javax.swing.JMenuItem();
        jMenuItemEditSuppliers1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRemoveSupplier = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSupplierDrug = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemViewDrugs = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAddNewDrug = new javax.swing.JMenuItem();
        jMenuItemModifyDrug = new javax.swing.JMenuItem();
        jMenuItemRemoveDrug = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDtockLevel = new javax.swing.JMenuItem();
        jMenuItemAddStock = new javax.swing.JMenuItem();
        jMenuItemSetDrugLimit = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCreateOrder = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemOptions = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDBConnection = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAdmin = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemPriceList = new javax.swing.JMenuItem();
        jMenuItemSupplierCostPrice = new javax.swing.JMenuItem();
        jMenuItemSalesReport = new javax.swing.JMenuItem();
        jMenuItemDrugLimitReport = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JayDee Pharmaceuticals");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtUserWelcome.setEditable(false);
        txtUserWelcome.setText("jTextField1");
        txtUserWelcome.setEnabled(false);
        txtUserWelcome.setBounds(500, 370, 300, 30);
        desktopPane.add(txtUserWelcome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/splash.png"))); // NOI18N
        lblUser.setText("Welcome User");
        lblUser.setBounds(380, 110, 300, 150);
        desktopPane.add(lblUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/Logout24.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/close_red.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);
        jToolBar1.add(jSeparator3);

        btnSupplierDrugList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/pills24.png"))); // NOI18N
        btnSupplierDrugList.setText("Supplier-DrugList");
        btnSupplierDrugList.setToolTipText("Click to set the supplier's druglist");
        btnSupplierDrugList.setFocusable(false);
        btnSupplierDrugList.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSupplierDrugList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierDrugListActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSupplierDrugList);

        btnInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/inventory.png"))); // NOI18N
        btnInventory.setText("Inventory");
        btnInventory.setFocusable(false);
        btnInventory.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInventory);
        jToolBar1.add(jSeparator10);

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/credit-cards.png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setEnabled(false);
        btnAdmin.setFocusable(false);
        btnAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdmin);
        jToolBar1.add(jSeparator9);

        btnPOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/checkout.png"))); // NOI18N
        btnPOS.setText("POS");
        btnPOS.setFocusable(false);
        btnPOS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOSActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPOS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        jMenuItemPOS.setText("POS");
        jMenuItemPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPOSActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemPOS);
        fileMenu.add(jSeparator11);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemLogout);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu3.setText("Suppliers");

        jMenuItemViewSuppliers.setText("View Suppliers");
        jMenuItemViewSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewSuppliersActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemViewSuppliers);
        jMenu3.add(jSeparator4);

        jMenuItemAddNewSuppliers.setText("Add New Supplier");
        jMenuItemAddNewSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddNewSuppliersActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAddNewSuppliers);

        jMenuItemEditSuppliers.setText("Edit Suppliers");
        jMenuItemEditSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditSuppliersActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemEditSuppliers);
        jMenu3.add(jSeparator1);

        jMenuItemAddSupplier.setText("Add Supplier-Simplified");
        jMenuItemAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddSupplierActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAddSupplier);

        jMenuItemEditSuppliers1.setText("Edit Suppliers - Simplified");
        jMenuItemEditSuppliers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditSuppliers1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemEditSuppliers1);
        jMenu3.add(jSeparator2);

        jMenuItemRemoveSupplier.setText("Remove Supplier");
        jMenuItemRemoveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveSupplierActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRemoveSupplier);
        jMenu3.add(jSeparator6);

        jMenuItemSupplierDrug.setText("Supplier Drug");
        jMenuItemSupplierDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierDrugActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSupplierDrug);

        menuBar.add(jMenu3);

        jMenu4.setText("Drugs");

        jMenuItemViewDrugs.setText("View Drugs");
        jMenuItemViewDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewDrugsActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemViewDrugs);
        jMenu4.add(jSeparator5);

        jMenuItemAddNewDrug.setText("Add New Drug");
        jMenuItemAddNewDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddNewDrugActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAddNewDrug);

        jMenuItemModifyDrug.setText("Modify Drug");
        jMenuItemModifyDrug.setToolTipText("Modify Drug Details");
        jMenuItemModifyDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifyDrugActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemModifyDrug);

        jMenuItemRemoveDrug.setText("Remove Drug");
        jMenuItemRemoveDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveDrugActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRemoveDrug);

        menuBar.add(jMenu4);

        jMenu1.setText("Inventory");

        jMenuItemDtockLevel.setText("View Stock Level");
        jMenuItemDtockLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDtockLevelActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDtockLevel);

        jMenuItemAddStock.setText("Add Stock");
        jMenuItemAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddStockActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAddStock);

        jMenuItemSetDrugLimit.setText("Set DrugLimit");
        jMenuItemSetDrugLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetDrugLimitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSetDrugLimit);
        jMenu1.add(jSeparator12);

        jMenuItemCreateOrder.setText("Create Order");
        jMenuItemCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateOrderActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCreateOrder);

        menuBar.add(jMenu1);

        jMenu2.setText("Tools");

        jMenuItemOptions.setText("Options");
        jMenuItemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOptionsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemOptions);
        jMenu2.add(jSeparator7);

        jMenuItemDBConnection.setText("Database Connection");
        jMenuItemDBConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDBConnectionActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDBConnection);
        jMenu2.add(jSeparator8);

        jMenuItemAdmin.setText("Administrator");
        jMenuItemAdmin.setEnabled(false);
        jMenuItemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAdmin);

        menuBar.add(jMenu2);

        jMenu5.setText("Reports");

        jMenuItemPriceList.setText("PriceList Report");
        jMenuItemPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPriceListActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemPriceList);

        jMenuItemSupplierCostPrice.setText("Supplier Drug Report");
        jMenuItemSupplierCostPrice.setToolTipText("Compare Supplier price to our price");
        jMenuItemSupplierCostPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierCostPriceActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemSupplierCostPrice);

        jMenuItemSalesReport.setText("Sales Report");
        jMenuItemSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalesReportActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemSalesReport);

        jMenuItemDrugLimitReport.setText("Drug Limit Report");
        jMenuItemDrugLimitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDrugLimitReportActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDrugLimitReport);

        menuBar.add(jMenu5);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Are you sure you wish to log out? \nAny unsaved changes will be lost!","Log out...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            dispose();
            new Login().setVisible(true);
        }
}//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Are you sure you wish to exit? \nAny unsaved changes will be lost!","Exiting...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
}//GEN-LAST:event_btnExitActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
}//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Are you sure you wish to log out? \nAny unsaved changes will be lost!","Log out...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        if(end_of_init)
            new About().setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItemViewSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewSuppliersActionPerformed
        if(end_of_init){
            if(s_gui == null || s_gui.isClosed()){
                s_gui = new Supplier_GUI(false, "Information Message",user);
                this.desktopPane.add(s_gui, JLayeredPane.DEFAULT_LAYER);
                s_gui.setVisible(true);                
            }
            desktopPane.setSelectedFrame(s_gui);
        }
}//GEN-LAST:event_jMenuItemViewSuppliersActionPerformed

    private void jMenuItemAddNewSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddNewSuppliersActionPerformed
        if(end_of_init){
            if(s_gui == null || s_gui.isClosed()){
                s_gui = new Supplier_GUI(true, "Information Message",user);
                this.desktopPane.add(s_gui, JLayeredPane.DEFAULT_LAYER);
                s_gui.setVisible(true);
            }
            desktopPane.setSelectedFrame(s_gui);
        }
}//GEN-LAST:event_jMenuItemAddNewSuppliersActionPerformed

    private void jMenuItemRemoveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveSupplierActionPerformed
        if(end_of_init){
            if(s_gui == null || s_gui.isClosed()){
                s_gui = new Supplier_GUI(false, "Information Message",user);
                this.desktopPane.add(s_gui, JLayeredPane.DEFAULT_LAYER);
                s_gui.setVisible(true);
            }
            desktopPane.setSelectedFrame(s_gui);
        }
}//GEN-LAST:event_jMenuItemRemoveSupplierActionPerformed

    private void jMenuItemViewDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewDrugsActionPerformed
        if(end_of_init){
            if(d_editor == null || d_editor.isClosed()){
                d_editor = new DrugEditor(false, "Information Message", user);
                this.desktopPane.add(d_editor, JLayeredPane.DEFAULT_LAYER);
                d_editor.setVisible(true);
            }
            desktopPane.setSelectedFrame(d_editor);
        }
}//GEN-LAST:event_jMenuItemViewDrugsActionPerformed

    private void jMenuItemAddNewDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddNewDrugActionPerformed
        if(end_of_init){
            if(d_editor == null || d_editor.isClosed()){
                d_editor = new DrugEditor(true, "Information Message", user);
                this.desktopPane.add(d_editor, JLayeredPane.DEFAULT_LAYER);
                d_editor.setVisible(true);
            }
            desktopPane.setSelectedFrame(d_editor);
        }
}//GEN-LAST:event_jMenuItemAddNewDrugActionPerformed

    private void jMenuItemModifyDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifyDrugActionPerformed
       if(end_of_init){
            if(d_editor == null || d_editor.isClosed()){
                d_editor = new DrugEditor(true, "Information Message", user);
                this.desktopPane.add(d_editor, JLayeredPane.DEFAULT_LAYER);
                d_editor.setVisible(true);
            }
            desktopPane.setSelectedFrame(d_editor);
        }
}//GEN-LAST:event_jMenuItemModifyDrugActionPerformed

    private void jMenuItemRemoveDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveDrugActionPerformed
        if(end_of_init){
            if(d_editor == null || d_editor.isClosed()){
                d_editor = new DrugEditor(false, "Information Message", user);
                this.desktopPane.add(d_editor, JLayeredPane.DEFAULT_LAYER);
                d_editor.setVisible(true);
            }
            desktopPane.setSelectedFrame(d_editor);
        }
}//GEN-LAST:event_jMenuItemRemoveDrugActionPerformed

    private void jMenuItemAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddSupplierActionPerformed
        if(end_of_init){
            if(suppliers == null || suppliers.isClosed()){
                suppliers = new Suppliers(user);
                this.desktopPane.add(suppliers, JLayeredPane.DEFAULT_LAYER);
                suppliers.setVisible(true);
            }
            desktopPane.setSelectedFrame(suppliers);
        }
    }//GEN-LAST:event_jMenuItemAddSupplierActionPerformed

    private void jMenuItemEditSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditSuppliersActionPerformed
        if(end_of_init){
            if(s_gui == null || s_gui.isClosed()){
                s_gui = new Supplier_GUI(true, "Information Message",user);
                this.desktopPane.add(s_gui, JLayeredPane.DEFAULT_LAYER);
                s_gui.setVisible(true);
            }
            desktopPane.setSelectedFrame(s_gui);
        }
    }//GEN-LAST:event_jMenuItemEditSuppliersActionPerformed

    private void jMenuItemEditSuppliers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditSuppliers1ActionPerformed
        if(end_of_init){
            if(suppliers == null || suppliers.isClosed()){
                suppliers = new Suppliers(user);
                this.desktopPane.add(suppliers, JLayeredPane.DEFAULT_LAYER);
                suppliers.setVisible(true);
            }
            desktopPane.setSelectedFrame(suppliers);
        }
    }//GEN-LAST:event_jMenuItemEditSuppliers1ActionPerformed

    private void jMenuItemSupplierDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierDrugActionPerformed
        if(end_of_init){
            if(drug_supplier == null || drug_supplier.isClosed()){
                drug_supplier = new Drug_Supplier(user);
                this.desktopPane.add(drug_supplier, JLayeredPane.DEFAULT_LAYER);
                drug_supplier.setVisible(true);
            }
            desktopPane.setSelectedFrame(drug_supplier);
        }
    }//GEN-LAST:event_jMenuItemSupplierDrugActionPerformed

    private void btnSupplierDrugListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierDrugListActionPerformed
        if(end_of_init){
            if(drug_supplier == null || drug_supplier.isClosed()){
                drug_supplier = new Drug_Supplier(user);
                this.desktopPane.add(drug_supplier, JLayeredPane.DEFAULT_LAYER);
                drug_supplier.setVisible(true);
            }
            desktopPane.setSelectedFrame(drug_supplier);
        }
    }//GEN-LAST:event_btnSupplierDrugListActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        if(end_of_init){
            new Help().setVisible(true);
        }
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void jMenuItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOptionsActionPerformed
        if(end_of_init){
            new Options().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemOptionsActionPerformed

    private void jMenuItemDBConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDBConnectionActionPerformed
        if(end_of_init){
            new DBFuncGUI(new Info("Edit the value for the database connection")).setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemDBConnectionActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        if(end_of_init){
        if(main_admin == null){
            main_admin = new Main_Admin(); 
            desktopPane.add(main_admin); 
            main_admin.setVisible(true);
        }
        desktopPane.setSelectedFrame(main_admin);
        main_admin.setVisible(end_of_init);
       }
    }//GEN-LAST:event_btnAdminActionPerformed

    private void jMenuItemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminActionPerformed
       if(end_of_init){
        if(main_admin == null){
            main_admin = new Main_Admin(); 
            desktopPane.add(main_admin); 
            main_admin.setVisible(true);
        }
        desktopPane.setSelectedFrame(main_admin);
        main_admin.setVisible(end_of_init);
       }
    }//GEN-LAST:event_jMenuItemAdminActionPerformed

    private void btnPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOSActionPerformed
        if(end_of_init){
            if(pos == null || pos.isClosed()){
                pos = new POS(user);
                this.desktopPane.add(pos, JLayeredPane.DEFAULT_LAYER);
                pos.setVisible(true);
            }
            desktopPane.setSelectedFrame(pos);
        }
    }//GEN-LAST:event_btnPOSActionPerformed

    private void jMenuItemPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPOSActionPerformed
        if(end_of_init){
            if(pos == null || pos.isClosed()){
                pos = new POS(user);
                this.desktopPane.add(pos, JLayeredPane.DEFAULT_LAYER);
                pos.setVisible(true);
            }
            desktopPane.setSelectedFrame(pos);
        }
    }//GEN-LAST:event_jMenuItemPOSActionPerformed

    private void jMenuItemCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateOrderActionPerformed
         if(end_of_init){
            if(order_gui == null || order_gui.isClosed()){
                order_gui = new Order_GUI(user);
                this.desktopPane.add(order_gui, JLayeredPane.DEFAULT_LAYER);
                order_gui.setVisible(true);
            }
            desktopPane.setSelectedFrame(order_gui);
        }
    }//GEN-LAST:event_jMenuItemCreateOrderActionPerformed

    private void jMenuItemDtockLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDtockLevelActionPerformed
        if(end_of_init){
            if(inventory == null || inventory.isClosed()){
                inventory = new Inventory_UI();
                this.desktopPane.add(inventory, JLayeredPane.DEFAULT_LAYER);
                inventory.setVisible(true);
            }
            desktopPane.setSelectedFrame(inventory);
        }
    }//GEN-LAST:event_jMenuItemDtockLevelActionPerformed

    private void jMenuItemAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddStockActionPerformed
        if(end_of_init){
            if(inventory == null || inventory.isClosed()){
                inventory = new Inventory_UI();
                this.desktopPane.add(inventory, JLayeredPane.DEFAULT_LAYER);
                inventory.setVisible(true);
            }
            desktopPane.setSelectedFrame(inventory);
        }
    }//GEN-LAST:event_jMenuItemAddStockActionPerformed

    private void jMenuItemSetDrugLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetDrugLimitActionPerformed
        if(end_of_init){
            if(inventory == null || inventory.isClosed()){
                inventory = new Inventory_UI();
                this.desktopPane.add(inventory, JLayeredPane.DEFAULT_LAYER);
                inventory.setVisible(true);
            }
            desktopPane.setSelectedFrame(inventory);
        }
    }//GEN-LAST:event_jMenuItemSetDrugLimitActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
       if(end_of_init){
            if(inventory == null || inventory.isClosed()){
                inventory = new Inventory_UI();
                this.desktopPane.add(inventory, JLayeredPane.DEFAULT_LAYER);
                inventory.setVisible(true);
            }
            desktopPane.setSelectedFrame(inventory);
        }
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void jMenuItemPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPriceListActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                 new PriceList().print();
            }
        });
    }//GEN-LAST:event_jMenuItemPriceListActionPerformed

    private void jMenuItemSupplierCostPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierCostPriceActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                 new Supplier_Drug_List().print();
            }
        });
    }//GEN-LAST:event_jMenuItemSupplierCostPriceActionPerformed

    private void jMenuItemSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalesReportActionPerformed
        
         java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SalesReport().print();
            }
        });
    }//GEN-LAST:event_jMenuItemSalesReportActionPerformed

    private void jMenuItemDrugLimitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDrugLimitReportActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InventoryReport().print();
            }
        });
    }//GEN-LAST:event_jMenuItemDrugLimitReportActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String [] args) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new MainForm(new User(1)).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPOS;
    private javax.swing.JButton btnSupplierDrugList;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItemAddNewDrug;
    private javax.swing.JMenuItem jMenuItemAddNewSuppliers;
    private javax.swing.JMenuItem jMenuItemAddStock;
    private javax.swing.JMenuItem jMenuItemAddSupplier;
    private javax.swing.JMenuItem jMenuItemAdmin;
    private javax.swing.JMenuItem jMenuItemCreateOrder;
    private javax.swing.JMenuItem jMenuItemDBConnection;
    private javax.swing.JMenuItem jMenuItemDrugLimitReport;
    private javax.swing.JMenuItem jMenuItemDtockLevel;
    private javax.swing.JMenuItem jMenuItemEditSuppliers;
    private javax.swing.JMenuItem jMenuItemEditSuppliers1;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemModifyDrug;
    private javax.swing.JMenuItem jMenuItemOptions;
    private javax.swing.JMenuItem jMenuItemPOS;
    private javax.swing.JMenuItem jMenuItemPriceList;
    private javax.swing.JMenuItem jMenuItemRemoveDrug;
    private javax.swing.JMenuItem jMenuItemRemoveSupplier;
    private javax.swing.JMenuItem jMenuItemSalesReport;
    private javax.swing.JMenuItem jMenuItemSetDrugLimit;
    private javax.swing.JMenuItem jMenuItemSupplierCostPrice;
    private javax.swing.JMenuItem jMenuItemSupplierDrug;
    private javax.swing.JMenuItem jMenuItemViewDrugs;
    private javax.swing.JMenuItem jMenuItemViewSuppliers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField txtUserWelcome;
    // End of variables declaration//GEN-END:variables
}
